[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.16.0"              #sdk 35버전 호환 1.17.0 -> 1.16.0 변경
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.10.1"      #sdk 35버전 호환 1.12.0 -> 1.10.0 변경
composeBom = "2024.09.00"       #Compose UI 1.7.x 대응
room = "2.6.1"                  #Room 라이브러리 SDK35 호환 안정화 버전
ksp = "2.0.21-1.0.28"           #ksp 라이브러리 kotlin 2.0.21 호환 버전
hilt = "2.51.1"                 #Dagger Hilt 라이브러리 (DI) SDK35 및 최신 AGP와 호환 버전
workRuntimeKtx = "2.11.0"       #WorkManager (백그라운드) SDK 및 Kotlin 호환 버전
hiltNavigationCompose = "1.2.0"
navigationCompose = "2.8.5"     #Navigation 라이브러리 kotlin, sSDK, compose bom 호환 버전
serialization = "2.0.21"
foundation = "1.10.0"
googleGmsGoogleServices = "4.4.4"
firebaseFirestore = "26.1.0"        #Serialization 라이브러리 kotlin 호환 버전


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
# Hilt DI
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
# WorkManager
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
# Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose"}
# Serialization 런타임 라이브러리 추가
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.7.3" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# KSP 플러그인 정의
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
# Hilt DI 플러그인 정의
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
# Serialization 런타임 라이브러리 -> 컴파일 타임에 직렬화 로직 생성
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization"}
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }